// This file is regenerated by Desktop Studio : modify it carefully !

popup = POPUPS.myPopup = POPUPS.popup({ myPopup: {
	template: e.popup.template.NoButton,
	url: "myPopup\\popup.html",
	CX: 500,
	CY: 300,
	X: e.popup.position.Center,
	Y: e.popup.position.Center
}});

GLOBAL.events.START.on(function (ev) {
	if (ctx.options.isDebug) {
		systray.addMenu("", "TestPopup", "Test popups");
		systray.addMenu("TestPopup", "myPopupOpen" , "Open myPopup", "", function(ev) {
			POPUPS.myPopup.open({ testMode: true });
		});
		systray.addMenu("TestPopup", "myPopupClose" , "Close myPopup", "", function(ev) {
			POPUPS.myPopup.close();
		});
	}
});

POPUPS.myPopup.onTest(function(popup) {	
	// TODO : add your tests here
});

popup.item({ container1: {
	type: e.item.type.container,
	auto: true,
	fluid: true,
	background: e.item.style.None,
	parent: ""
}});

